### ISSUE TITLE
BMP280 pressor sensor

### ISSUE THREAD

**Issue by ramunigari** [BoschSensortec/BMP280_driver#1]
Hi all,

I am try to up the bmp280 pressure sensor with I2C interface using keil IDE and also downloaded the BMP280_driver code and initialize the bmp_init() and run it.
But BMP_init function goes to the HardFault_Handler.
Please any one knows about this issue, suggest me the solution for this.

**Comment by BoschSensortec** [comment]
Please give more information for your questions.  Or paste your code for the init here with error messages.

**Comment by ramunigari** [comment]
The below code is the initialization of the bmp_int(). when i run the code and at the read chip id status in the bmp280_init(), that was in  HardFault_Handler.i took the code from the GitHub(BoschSensortec/BMP280_Driver).

Please resolve this problem.

int main(void)
{
	struct bmp280_t   p_bmp280;
	sys_ticks_init();
	ret = WyzBeeI2c_Init((WyzBeeI2c_Config_t *) &config); /*Initialise I2C*/
	
	if(ret == 0)
	{	
		bmp280_init(&p_bmp280);
	}
}
 

BMP280_RETURN_FUNCTION_TYPE bmp280_init(struct bmp280_t *bmp280)
{
	/* variable used to return communication result*/
	BMP280_RETURN_FUNCTION_TYPE com_rslt = ERROR;
	u8 v_data_u8 = BMP280_INIT_VALUE;
  	
	p_bmp280 = bmp280;/* assign BMP280 ptr */
	
	/* read chip id */
	com_rslt = p_bmp280->BMP280_BUS_READ_FUNC(p_bmp280->dev_addr,	BMP280_CHIP_ID_REG, &v_data_u8,BMP280_INIT_VALUE);/* read Chip Id */
	p_bmp280->chip_id = v_data_u8;
	/* readout bmp280 calibparam structure */
	com_rslt += bmp280_get_calib_param();
	return com_rslt;
}

**Comment by BoschSensortec** [comment]
Dear  Customer,
     To identify the root cause of the problem. Please provide the below data.
            
    1) The I2C initialization function where the Bus functions are mapped ?
    2) The  error log which you are getting.      
             
    Note: In the code which  you  have pasted, In the bmp280_init(struct bmp280_t bmp280) function,
    the pointer is missing in the argument. This will give  compilation problem.
