### ISSUE TITLE
BMP280_ONE_U8X missing?

### ISSUE THREAD

**Issue by szufnarowski** [BoschSensortec/BMP280_driver#3]
Hi,
in the support-file there are two defines BMP280_ONE_U8X and BMP280_TWO_U8X used, however, those are not defined anywhere.
What value should they have? Can you correct this please?
Karl

**Comment by BoschSensortec** [comment]
Thanks for your feedback. Please take the following values for the missing defines.
  BMP280_ONE_U8X  - >  0x01
  BMP280_TWO_U8X ->  0x02
We will fix this in the next release.
Thank you.

**Comment by BoschSensortec** [comment]
Issue is already fixed in latest version.
