### ISSUE TITLE
BMP280 SPI Init

### ISSUE THREAD

**Issue by kleszcz10** [BoschSensortec/BMP280_driver#5]
Hi,

Could you write for me some example of initialize BMP280 and read temperature and pressure value ?
I try to use your support file but my code didn't work :/

**Comment by BoschSensortec** [comment]
Hi, Could you please let us know what problem you are facing in the code?
Are you able to read the chip-id of bmp280 sensor by using  bmp280_init() ?

**Comment by BoschSensortec** [comment]
We are closing this issue since we don't get feedback for long time,
