### ISSUE TITLE
Separate Communications from Computation

### ISSUE THREAD

**Issue by razed11** [BoschSensortec/BMP280_driver#7]
I attempted to use this library and had to abandon it. I have a communication scheme that will not fit with the assumption the library makes with simple blocking calls. If the computation code had been separated then I could have just used those functions. For example offer the ability to pass the compensation structure to the library and then make the calls for compensated temperature and pressure. Leave the data gather to the client.

**Comment by BoschSensortec** [comment]
Thanks for your feedback.
We have separate APIs for reading raw values for temperature & pressure (uncompensated). 
Later the raw values shall be compensated using the compensation related APIs mentioned below.
bmp280_compensate_temperature_int32
bmp280_compensate_pressure_int32 

Please let us know if you need any further clarifications.
