### ISSUE TITLE
Not accepted data while writing to Register 0xF4 “ctrl_meas”

### ISSUE THREAD

**Issue by bar-bog** [BoschSensortec/BMP280_driver#8]
Dear Bosch Sensortec team,
I'm using the driver for BMP280 driver and observed some behavior that I'm not able to understand.
# Introduction

I'm using the example code in bmp280_support file and function bmp280_set_power_mode sets register 0xF4 to 0x03 which is the NORMAL_MODE.
After that bmp280_set_work_mode tries to set ULTRA_LOW_POWER_MODE and to do that it reads out the 0xF4 register contents and performs OR operation and tries to write 0x27 value (which is correct). However when I read out the data after writing the 0x27 value it's still 0x03.
# Study

So I've implemented a while loop that tries to write the value until it's actually stored in the sensor. And the retries are visible on the logic analyzer.
![image](https://cloud.githubusercontent.com/assets/18262496/18666757/cd80020c-7f2d-11e6-86eb-7b1cb3319eaf.png)

Is it a normal behavior of the device? Could you advise me what to do to get rid of those retries ?
Please let me know if any more details are needed, thanks.

**Comment by BoschSensortec** [comment]
Thanks for your comments.
Could you please try the below sequence.
set work mode first and then set power mode.
